# Generated by Django 2.2.9 on 2020-01-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_unique_email', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
